"""Add foto_profil column to karyawan

Revision ID: 570600f3dba4
Revises: 83a47d910d6b
Create Date: 2025-11-09 00:55:38.987573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570600f3dba4'
down_revision = '83a47d910d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_profil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.drop_column('foto_profil')

    # ### end Alembic commands ###
