"""initial tables

Revision ID: 83a47d910d6b
Revises: 
Create Date: 2025-11-07 00:21:55.658623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a47d910d6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aset_tetap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_aset', sa.String(length=100), nullable=False),
    sa.Column('manufaktur', sa.String(length=100), nullable=True),
    sa.Column('tanggal_perolehan', sa.Date(), nullable=False),
    sa.Column('harga_perolehan', sa.Float(), nullable=False),
    sa.Column('umur_ekonomis', sa.Integer(), nullable=False),
    sa.Column('nilai_sisa', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('nama_barang', sa.String(length=200), nullable=False),
    sa.Column('jenis', sa.String(length=100), nullable=False),
    sa.Column('jumlah', sa.String(length=50), nullable=True),
    sa.Column('satuan', sa.String(length=50), nullable=True),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('keterangan', sa.String(length=200), nullable=True),
    sa.Column('catatan_tambahan', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faktur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_faktur', sa.String(length=50), nullable=False),
    sa.Column('nama_pelanggan', sa.String(length=100), nullable=False),
    sa.Column('tanggal_faktur', sa.Date(), nullable=False),
    sa.Column('alamat_pelanggan', sa.Text(), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('total_harga', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomor_faktur')
    )
    op.create_table('karyawan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('jabatan', sa.String(length=100), nullable=False),
    sa.Column('divisi', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('gaji_pokok', sa.Float(), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('no_telepon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('bank', sa.String(length=50), nullable=True),
    sa.Column('no_rekening', sa.String(length=50), nullable=True),
    sa.Column('npwp', sa.String(length=25), nullable=True),
    sa.Column('pendidikan_terakhir', sa.String(length=50), nullable=True),
    sa.Column('status_perkawinan', sa.String(length=20), nullable=True),
    sa.Column('tanggal_masuk', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    op.create_table('kasbon_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_utang', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_rab', sa.String(length=50), nullable=False),
    sa.Column('nama_proyek', sa.String(length=100), nullable=False),
    sa.Column('nama_klien', sa.String(length=100), nullable=False),
    sa.Column('lokasi_proyek', sa.String(length=200), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_anggaran', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_rab')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('item_faktur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faktur_id', sa.Integer(), nullable=False),
    sa.Column('nama_barang', sa.String(length=200), nullable=False),
    sa.Column('jumlah', sa.Float(), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['faktur_id'], ['faktur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_rab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rab_id', sa.Integer(), nullable=False),
    sa.Column('kategori_item', sa.String(length=100), nullable=False),
    sa.Column('nama_item', sa.String(length=200), nullable=False),
    sa.Column('spesifikasi', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('satuan', sa.String(length=50), nullable=False),
    sa.Column('harga_satuan', sa.Float(), nullable=False),
    sa.Column('total_harga', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['rab_id'], ['rab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slip_gaji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('periode', sa.String(length=7), nullable=False),
    sa.Column('gaji_pokok', sa.Float(), nullable=False),
    sa.Column('tunjangan', sa.Float(), nullable=True),
    sa.Column('bonus', sa.Float(), nullable=True),
    sa.Column('potongan', sa.Float(), nullable=True),
    sa.Column('total_gaji', sa.Float(), nullable=False),
    sa.Column('keterangan_tunjangan', sa.Text(), nullable=True),
    sa.Column('keterangan_potongan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.Column('tanggal_dibayar', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slip_gaji')
    op.drop_table('item_rab')
    op.drop_table('item_faktur')
    op.drop_table('user')
    op.drop_table('rab')
    op.drop_table('kasbon_state')
    op.drop_table('karyawan')
    op.drop_table('faktur')
    op.drop_table('cashflow')
    op.drop_table('aset_tetap')
    # ### end Alembic commands ###
